---

language: python
services: docker

env:
  global:
    - ROLE_NAME: first5rootmail
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/

# yamllint disable rule:line-length
notifications:
  slack:
    secure: XvcVmr2EOWHdaZZFE3LFvmo01hE1KvcIgGNdoTGroUZXst05NhtyXGgPjzdBUkuRJDzGbFfHzZZO99cOK7/Ef9+R5J7hcenb/52Gb7z3V0PyAlL1z0h1EEJxgcbB8oPuDd6y2Jvtw5j4++5izsaKfiqS3B49jYGPzKD77ykPi/OIoGVsq2tSLdBg1bzXyzkTG2hoqEPhAqWquloU5Y8y0ZgVO07Xwhgfe1DldDXwMBtvQtom/nzbmCtRTEc24HReaKxyjK5OxAaSI5yXk1nezqiIwlgi3tOWbOAzOJpyVS+tgAeC7a4w4fFSkIsseQwhnNDyqpsvxeQOup6MbFY/NPnn9mnmO7Onoy7ExHerhK0MylxTpy4jxCA0gVNvyFSKGbkwvJ2J1VByNdhyilcERaxFHBXOQl0QvKyuXJ4QheBIr9lzhZVyFgDV/MggTKtaESUaDL2PJykBw2AF0DEgg1c5mlDQ3oYvFHIgj9tHbCLj6/SIXwJOacD08A2ufq1RpMb4zCbBpORiokApOji4+nk9Aybfu2wWUrkc7t+1DJqAwLhopoJY78Xqp/jX3BhN1npgs5nUq3Gkh+YJVBO9j0WJlDOAdjvzdQ+u92siNvQUDjVemzL9ngbTCQrBsTfrf9ov1cggtuf8I8/Gjvy6HrR78v5adyLoms5F1mLBOng=
# yamllint enable rule:line-length
